
package com.hoau.hoauapp.si.dc.company;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-15T09:12:56.107+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class CompanyServices_CompanyServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.szzc.com.cn/services/CompanyServices", "CompanyServices");

    private CompanyServices_CompanyServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CompanyServices_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CompanyServices_Service ss = new CompanyServices_Service(wsdlURL, SERVICE_NAME);
        CompanyServices port = ss.getCompanyServicesPort();  
        
        {
        System.out.println("Invoking getCompanyData...");
        com.hoau.hoauapp.si.dc.company.CompanyData _getCompanyData__return = port.getCompanyData();
        System.out.println("getCompanyData.result=" + _getCompanyData__return);


        }

        System.exit(0);
    }

}
