
package com.hoau.hoauapp.si.dc.couponclipping;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-21T08:42:14.908+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class OuterVocherServices_OuterVocherServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.hoau.net/services/OuterVocherServices", "OuterVocherServices");

    private OuterVocherServices_OuterVocherServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OuterVocherServices_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OuterVocherServices_Service ss = new OuterVocherServices_Service(wsdlURL, SERVICE_NAME);
        OuterVocherServices port = ss.getOuterVocherServicesPort();  
        
        {
        System.out.println("Invoking getVoucherStatus...");
        java.lang.String _getVoucherStatus_arg0 = "";
        java.util.List<java.lang.String> _getVoucherStatus_arg1 = null;
        com.hoau.hoauapp.si.dc.couponclipping.GetVoucherStatusRes _getVoucherStatus__return = port.getVoucherStatus(_getVoucherStatus_arg0, _getVoucherStatus_arg1);
        System.out.println("getVoucherStatus.result=" + _getVoucherStatus__return);


        }
        {
        System.out.println("Invoking getNewVoucher...");
        java.lang.String _getNewVoucher_arg0 = "";
        int _getNewVoucher_arg1 = 0;
        com.hoau.hoauapp.si.dc.couponclipping.VoucherInfo _getNewVoucher__return = port.getNewVoucher(_getNewVoucher_arg0, _getNewVoucher_arg1);
        System.out.println("getNewVoucher.result=" + _getNewVoucher__return);


        }
        {
        System.out.println("Invoking getUsedVouchers...");
        java.lang.String _getUsedVouchers_arg0 = "";
        java.lang.String _getUsedVouchers_arg1 = "";
        java.lang.String _getUsedVouchers_arg2 = "";
        java.util.List<java.lang.String> _getUsedVouchers__return = port.getUsedVouchers(_getUsedVouchers_arg0, _getUsedVouchers_arg1, _getUsedVouchers_arg2);
        System.out.println("getUsedVouchers.result=" + _getUsedVouchers__return);


        }

        System.exit(0);
    }

}
