
package com.hoau.hoauapp.si.dc.couponclipping;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-21T08:42:14.947+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class OuterVocherServices_OuterVocherServicesPort_Server{

    protected OuterVocherServices_OuterVocherServicesPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new OuterVocherServicesImpl();
        String address = "http://10.39.251.3:8080/hoaunew/services/OuterVocherServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new OuterVocherServices_OuterVocherServicesPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
