package com.hoau.hoauapp.si.dc.couponclipping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-21T08:42:14.941+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.hoau.net/services/OuterVocherServices", name = "OuterVocherServices")
@XmlSeeAlso({ObjectFactory.class})
public interface OuterVocherServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVoucherStatus", targetNamespace = "http://www.hoau.net/services/OuterVocherServices", className = "com.hoau.hoauapp.si.dc.couponclipping.GetVoucherStatus")
    @WebMethod
    @ResponseWrapper(localName = "getVoucherStatusResponse", targetNamespace = "http://www.hoau.net/services/OuterVocherServices", className = "com.hoau.hoauapp.si.dc.couponclipping.GetVoucherStatusResponse")
    public com.hoau.hoauapp.si.dc.couponclipping.GetVoucherStatusRes getVoucherStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNewVoucher", targetNamespace = "http://www.hoau.net/services/OuterVocherServices", className = "com.hoau.hoauapp.si.dc.couponclipping.GetNewVoucher")
    @WebMethod
    @ResponseWrapper(localName = "getNewVoucherResponse", targetNamespace = "http://www.hoau.net/services/OuterVocherServices", className = "com.hoau.hoauapp.si.dc.couponclipping.GetNewVoucherResponse")
    public com.hoau.hoauapp.si.dc.couponclipping.VoucherInfo getNewVoucher(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsedVouchers", targetNamespace = "http://www.hoau.net/services/OuterVocherServices", className = "com.hoau.hoauapp.si.dc.couponclipping.GetUsedVouchers")
    @WebMethod
    @ResponseWrapper(localName = "getUsedVouchersResponse", targetNamespace = "http://www.hoau.net/services/OuterVocherServices", className = "com.hoau.hoauapp.si.dc.couponclipping.GetUsedVouchersResponse")
    public java.util.List<java.lang.String> getUsedVouchers(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
