package com.hoau.hoauapp.si.dc.couponclipping;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-21T08:42:14.952+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "OuterVocherServices", 
                  wsdlLocation = "http://10.39.251.3:8080/hoaunew/services/OuterVocherServices?wsdl",
                  targetNamespace = "http://www.hoau.net/services/OuterVocherServices") 
public class OuterVocherServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.hoau.net/services/OuterVocherServices", "OuterVocherServices");
    public final static QName OuterVocherServicesPort = new QName("http://www.hoau.net/services/OuterVocherServices", "OuterVocherServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.3:8080/hoaunew/services/OuterVocherServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OuterVocherServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.3:8080/hoaunew/services/OuterVocherServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OuterVocherServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OuterVocherServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OuterVocherServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OuterVocherServices
     */
    @WebEndpoint(name = "OuterVocherServicesPort")
    public OuterVocherServices getOuterVocherServicesPort() {
        return super.getPort(OuterVocherServicesPort, OuterVocherServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OuterVocherServices
     */
    @WebEndpoint(name = "OuterVocherServicesPort")
    public OuterVocherServices getOuterVocherServicesPort(WebServiceFeature... features) {
        return super.getPort(OuterVocherServicesPort, OuterVocherServices.class, features);
    }

}
