
package com.hoau.hoauapp.si.ttq;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-09T14:20:02.978+08:00
 * Generated source version: 3.0.1
 * 
 */
 
public class FoxServicePortType_FoxServiceHttpPort_Server{

    protected FoxServicePortType_FoxServiceHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new FoxServiceHttpPortImpl();
        String address = "http://10.39.251.105/HOAU_OL/services/FoxService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new FoxServicePortType_FoxServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
