package com.hoau.hoauapp.si.dc.sendme;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-06-16T15:49:23.708+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.hoau.net/services/AppWaybillServices", name = "AppWaybillServices")
@XmlSeeAlso({ObjectFactory.class})
public interface AppWaybillServices {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://www.hoau.net/services/AppWaybillServices/AppWaybillServices/queryWBlistRequest", output = "http://www.hoau.net/services/AppWaybillServices/AppWaybillServices/queryWBlistResponse")
    @RequestWrapper(localName = "queryWBlist", targetNamespace = "http://www.hoau.net/services/AppWaybillServices", className = "com.hoau.hoauapp.si.dc.sendme.QueryWBlist")
    @WebMethod
    @ResponseWrapper(localName = "queryWBlistResponse", targetNamespace = "http://www.hoau.net/services/AppWaybillServices", className = "com.hoau.hoauapp.si.dc.sendme.QueryWBlistResponse")
    public com.hoau.hoauapp.si.dc.sendme.WaybillInfoVector queryWBlist(
        @WebParam(name = "registerPhone", targetNamespace = "")
        java.lang.String registerPhone
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://www.hoau.net/services/AppWaybillServices/AppWaybillServices/queryWayBillRequest", output = "http://www.hoau.net/services/AppWaybillServices/AppWaybillServices/queryWayBillResponse")
    @RequestWrapper(localName = "queryWayBill", targetNamespace = "http://www.hoau.net/services/AppWaybillServices", className = "com.hoau.hoauapp.si.dc.sendme.QueryWayBill")
    @WebMethod
    @ResponseWrapper(localName = "queryWayBillResponse", targetNamespace = "http://www.hoau.net/services/AppWaybillServices", className = "com.hoau.hoauapp.si.dc.sendme.QueryWayBillResponse")
    public com.hoau.hoauapp.si.dc.sendme.WaybillInfo queryWayBill(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
