
package com.hoau.hoauapp.si.claim;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-07T10:10:22.483+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class ClaimsWSService_ClaimsWSServiceImplPort_Server{

    protected ClaimsWSService_ClaimsWSServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ClaimsWSServiceImpl();
        String address = "http://10.39.116.47:8080/TDHY_CLAIMS/ws-services/claimsWSService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ClaimsWSService_ClaimsWSServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
