
package com.hoau.hoauapp.si.ol;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DistrictService", targetNamespace = "http://service.server.itf.module.obh.hoau.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DistrictService {


    /**
     * 
     * @return
     *     returns java.util.List<com.hoau.hoauapp.si.ol.DistrictModelHot>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryHotCity", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryHotCity")
    @ResponseWrapper(localName = "queryHotCityResponse", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryHotCityResponse")
    public List<DistrictModelHot> queryHotCity();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hoau.hoauapp.si.ol.DistrictModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCityByProvince", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryCityByProvince")
    @ResponseWrapper(localName = "queryCityByProvinceResponse", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryCityByProvinceResponse")
    public List<DistrictModel> queryCityByProvince(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryDeptByDistrict", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryDeptByDistrict")
    @ResponseWrapper(localName = "queryDeptByDistrictResponse", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryDeptByDistrictResponse")
    public String queryDeptByDistrict(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @return
     *     returns java.util.List<com.hoau.hoauapp.si.ol.DistrictModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryProvince", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryProvince")
    @ResponseWrapper(localName = "queryProvinceResponse", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryProvinceResponse")
    public List<DistrictModel> queryProvince();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.hoau.hoauapp.si.ol.DistrictModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryCountyByCity", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryCountyByCity")
    @ResponseWrapper(localName = "queryCountyByCityResponse", targetNamespace = "http://service.server.itf.module.obh.hoau.com/", className = "com.hoau.hoauapp.si.ol.QueryCountyByCityResponse")
    public List<DistrictModel> queryCountyByCity(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
