package com.hoau.hoauapp.si.ol;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-10-29T15:52:16.555+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://services.district.interfaces.sinotrans.com", name = "DistrictServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DistrictServicePortType {

    @WebResult(name = "out", targetNamespace = "http://services.district.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryProvince", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryProvince")
    @WebMethod
    @ResponseWrapper(localName = "queryProvinceResponse", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryProvinceResponse")
    public com.hoau.hoauapp.si.ol.ArrayOfDistrictModel queryProvince();

    @WebResult(name = "out", targetNamespace = "http://services.district.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryCityByProvince", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryCityByProvince")
    @WebMethod
    @ResponseWrapper(localName = "queryCityByProvinceResponse", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryCityByProvinceResponse")
    public com.hoau.hoauapp.si.ol.ArrayOfDistrictModel queryCityByProvince(
        @WebParam(name = "in0", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.district.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryDeptByDistrict", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryDeptByDistrict")
    @WebMethod
    @ResponseWrapper(localName = "queryDeptByDistrictResponse", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryDeptByDistrictResponse")
    public java.lang.String queryDeptByDistrict(
        @WebParam(name = "in0", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in2,
        @WebParam(name = "in3", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in3,
        @WebParam(name = "in4", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in4,
        @WebParam(name = "in5", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in5
    );

    @WebResult(name = "out", targetNamespace = "http://services.district.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryCountyByCity", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryCountyByCity")
    @WebMethod
    @ResponseWrapper(localName = "queryCountyByCityResponse", targetNamespace = "http://services.district.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ol.QueryCountyByCityResponse")
    public com.hoau.hoauapp.si.ol.ArrayOfDistrictModel queryCountyByCity(
        @WebParam(name = "in0", targetNamespace = "http://services.district.interfaces.sinotrans.com")
        java.lang.String in0
    );
}
