
package com.hoau.hoauapp.si.ol;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.hoau.hoauapp.constant.PropertyConstant;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DistrictService", targetNamespace = "http://district.impl.service.server.itf.module.obh.hoau.com/", wsdlLocation = "http://online.hoau.net/obh-web/services/DistrictService?wsdl")
public class DistrictService_Service
    extends Service
{

    private final static URL DISTRICTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.hoau.hoauapp.si.ol.DistrictService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.hoau.hoauapp.si.ol.DistrictService_Service.class.getResource(".");
            url = new URL(baseUrl, PropertyConstant.DISTRICT_URL);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://online.hoau.net/obh-web/services/DistrictService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DISTRICTSERVICE_WSDL_LOCATION = url;
    }

    public DistrictService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DistrictService_Service() {
        super(DISTRICTSERVICE_WSDL_LOCATION, new QName("http://district.impl.service.server.itf.module.obh.hoau.com/", "DistrictService"));
    }

    /**
     * 
     * @return
     *     returns DistrictService
     */
    @WebEndpoint(name = "DistrictServiceImplPort")
    public DistrictService getDistrictServiceImplPort() {
        return super.getPort(new QName("http://district.impl.service.server.itf.module.obh.hoau.com/", "DistrictServiceImplPort"), DistrictService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DistrictService
     */
    @WebEndpoint(name = "DistrictServiceImplPort")
    public DistrictService getDistrictServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://district.impl.service.server.itf.module.obh.hoau.com/", "DistrictServiceImplPort"), DistrictService.class, features);
    }

}
