
package com.hoau.hoauapp.si.ol;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-10-29T15:52:16.496+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class DistrictServicePortType_DistrictServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.district.interfaces.sinotrans.com", "DistrictService");

    private DistrictServicePortType_DistrictServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        String str = new DistrictService_Service().getDistrictServiceImplPort().queryDeptByDistrict("上海市","上海市","闵行区","121.309619","31.210529","20");
        System.out.println(str);
    }

}
