package com.hoau.hoauapp.si.newoms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-12-08T11:16:51.517+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "AppService", 
                  wsdlLocation = "http://10.39.251.184:8180/obh-web/services/AppService?wsdl",
                  targetNamespace = "http://app.impl.service.server.itf.module.obh.hoau.com/") 
public class AppService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://app.impl.service.server.itf.module.obh.hoau.com/", "AppService");
    public final static QName AppServiceImplPort = new QName("http://app.impl.service.server.itf.module.obh.hoau.com/", "AppServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.184:8180/obh-web/services/AppService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AppService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.184:8180/obh-web/services/AppService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AppService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServiceImplPort")
    public AppService getAppServiceImplPort() {
        return super.getPort(AppServiceImplPort, AppService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServiceImplPort")
    public AppService getAppServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AppServiceImplPort, AppService.class, features);
    }

}
