
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.hoauapp.si.newoms;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-11-04T11:58:01.487+08:00
 * Generated source version: 2.7.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "AppService",
                      portName = "AppServiceHttpPort",
                      targetNamespace = "http://services.app.interfaces.sinotrans.com",
                      wsdlLocation = "http://10.39.117.117:8081/HOAU_OL/services/AppService?wsdl",
                      endpointInterface = "com.hoau.hoauapp.si.newoms.AppServicePortType")
                      
public class AppServicePortTypeImpl implements AppServicePortType {

    private static final Logger LOG = Logger.getLogger(AppServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.newoms.AppServicePortType#createOrder(com.hoau.hoauapp.si.newoms.OrderModel  in0 )*
     */
    public com.hoau.hoauapp.si.newoms.PhoneOrderResModel createOrder(com.hoau.hoauapp.si.newoms.OrderModel in0) { 
        LOG.info("Executing operation createOrder");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.newoms.PhoneOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.newoms.AppServicePortType#queryOrder(com.hoau.hoauapp.si.newoms.QueryOrdersReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.newoms.QueryAppOrdersResModel queryOrder(com.hoau.hoauapp.si.newoms.QueryOrdersReqModel in0) { 
        LOG.info("Executing operation queryOrder");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.newoms.QueryAppOrdersResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.newoms.AppServicePortType#modifyOrder(com.hoau.hoauapp.si.newoms.OrderModel  in0 )*
     */
    public com.hoau.hoauapp.si.newoms.ModifyOrderResModel modifyOrder(com.hoau.hoauapp.si.newoms.OrderModel in0) { 
        LOG.info("Executing operation modifyOrder");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.newoms.ModifyOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.newoms.AppServicePortType#queryUserInfo(java.lang.String  in0 )*
     */
    public com.hoau.hoauapp.si.newoms.QueryUserResModel queryUserInfo(java.lang.String in0) { 
        LOG.info("Executing operation queryUserInfo");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.newoms.QueryUserResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.newoms.AppServicePortType#resetPwd(com.hoau.hoauapp.si.newoms.ResetPwdReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.newoms.ResetPwdResModel resetPwd(com.hoau.hoauapp.si.newoms.ResetPwdReqModel in0) { 
        LOG.info("Executing operation resetPwd");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.newoms.ResetPwdResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
