package com.hoau.hoauapp.si.newoms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-11-04T11:58:01.525+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://services.app.interfaces.sinotrans.com", name = "AppServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface AppServicePortType {

    @WebResult(name = "out", targetNamespace = "http://services.app.interfaces.sinotrans.com")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.CreateOrder")
    @WebMethod
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.CreateOrderResponse")
    public com.hoau.hoauapp.si.newoms.PhoneOrderResModel createOrder(
        @WebParam(name = "in0", targetNamespace = "http://services.app.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.newoms.OrderModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.app.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryOrder", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.QueryOrder")
    @WebMethod
    @ResponseWrapper(localName = "queryOrderResponse", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.QueryOrderResponse")
    public com.hoau.hoauapp.si.newoms.QueryAppOrdersResModel queryOrder(
        @WebParam(name = "in0", targetNamespace = "http://services.app.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.newoms.QueryOrdersReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.app.interfaces.sinotrans.com")
    @RequestWrapper(localName = "modifyOrder", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.ModifyOrder")
    @WebMethod
    @ResponseWrapper(localName = "modifyOrderResponse", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.ModifyOrderResponse")
    public com.hoau.hoauapp.si.newoms.ModifyOrderResModel modifyOrder(
        @WebParam(name = "in0", targetNamespace = "http://services.app.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.newoms.OrderModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.app.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryUserInfo", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.QueryUserInfo")
    @WebMethod
    @ResponseWrapper(localName = "queryUserInfoResponse", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.QueryUserInfoResponse")
    public com.hoau.hoauapp.si.newoms.QueryUserResModel queryUserInfo(
        @WebParam(name = "in0", targetNamespace = "http://services.app.interfaces.sinotrans.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.app.interfaces.sinotrans.com")
    @RequestWrapper(localName = "resetPwd", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.ResetPwd")
    @WebMethod
    @ResponseWrapper(localName = "resetPwdResponse", targetNamespace = "http://services.app.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.newoms.ResetPwdResponse")
    public com.hoau.hoauapp.si.newoms.ResetPwdResModel resetPwd(
        @WebParam(name = "in0", targetNamespace = "http://services.app.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.newoms.ResetPwdReqModel in0
    );
}
