
package com.hoau.hoauapp.si.newoms;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-11-04T11:58:01.535+08:00
 * Generated source version: 2.7.14
 * 
 */
 
public class AppServicePortType_AppServiceHttpPort_Server{

    protected AppServicePortType_AppServiceHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new AppServicePortTypeImpl();
        String address = "http://10.39.117.117:8081/HOAU_OL/services/AppService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new AppServicePortType_AppServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
