
package com.hoau.hoauapp.si.claim;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.io.FileInputStream;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-05-07T10:10:22.434+08:00
 * Generated source version: 2.7.11
 * 
 */
public final class ClaimsWSService_ClaimsWSServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://hoauapp.ws.erry.com/", "ClaimsWSServiceImplService");

    private ClaimsWSService_ClaimsWSServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ClaimsWSServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ClaimsWSServiceImplService ss = new ClaimsWSServiceImplService(wsdlURL, SERVICE_NAME);
        ClaimsWSService port = ss.getClaimsWSServiceImplPort();  
        
//        {
//        System.out.println("Invoking getClaims...");
//        java.lang.String _getClaims_userID = "35379605";
//        com.hoau.hoauapp.si.claim.ResponseQueryClaims _getClaims__return = port.getClaims(_getClaims_userID);
//        System.out.println("getClaims.result=" + _getClaims__return);
//
//
//        }
//        {
//        System.out.println("Invoking confirmClaimsAmount...");
//        java.lang.String _confirmClaimsAmount_claimsNo = "";
//        com.hoau.hoauapp.si.claim.ResponseClaimsObject _confirmClaimsAmount__return = port.confirmClaimsAmount(_confirmClaimsAmount_claimsNo);
//        System.out.println("confirmClaimsAmount.result=" + _confirmClaimsAmount__return);
//
//
//        }
//        {
//        System.out.println("Invoking findByClaims...");
//        java.lang.String _findByClaims_billNo = "";
//        java.lang.String _findByClaims_claimsNo = "";
//        com.hoau.hoauapp.si.claim.ResponseQueryFiles _findByClaims__return = port.findByClaims(_findByClaims_billNo, _findByClaims_claimsNo);
//        System.out.println("findByClaims.result=" + _findByClaims__return);
//
//
//        }
        {
        System.out.println("Invoking uploadClaims...");
        ClaimsInfo ci = new ClaimsInfo();
        ci.setBillNo("B0000133");
        ci.setAccidentType("1");
        ci.setBillTel("15252996903");
        ci.setCargoType("2");
        ci.setClaimsAmount(new BigDecimal(100));
        ci.setClaimsOwner("田育林");
        ci.setContactName("田育林");
        ci.setContactTel("18200537093");
        ci.setCreateBy("35379605");
        ci.setExceptionCount(1L);
        ci.setPayeeName("");
        ci.setChannel(2);
        ci.setBankAccount("6222022306003076048");
        ci.setBankAccountName("12345");
        ci.setBankProvince("四川");
        ci.setBankCity("成都市");
        ci.setBankName("12345");
        com.hoau.hoauapp.si.claim.ClaimsInfo _uploadClaims_claimsInfo = ci;
        com.hoau.hoauapp.si.claim.ResponseClaimsObject _uploadClaims__return = port.uploadClaims(_uploadClaims_claimsInfo);
        System.out.println("uploadClaims.result=" + _uploadClaims__return);


        }
//        {
//        System.out.println("Invoking queryCheck...");
//        com.hoau.hoauapp.si.claim.ReqClaimsObject _queryCheck_reqClaimsObject = null;
//        com.hoau.hoauapp.si.claim.ResponseClaimsObject _queryCheck__return = port.queryCheck(_queryCheck_reqClaimsObject);
//        System.out.println("queryCheck.result=" + _queryCheck__return);
//
//
//        }

        System.exit(0);
    }

}
