package net.hoau.services.howpriceandtimequeryservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-04T17:46:03.922+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://www.hoau.net/services/HowPriceAndTimeQueryServices", name = "HowPriceAndTimeQueryServices")
@XmlSeeAlso({ObjectFactory.class})
public interface HowPriceAndTimeQueryServices {

    @WebMethod
    @RequestWrapper(localName = "queryPriceAndTime", targetNamespace = "http://www.hoau.net/services/HowPriceAndTimeQueryServices", className = "net.hoau.services.howpriceandtimequeryservices.QueryPriceAndTime")
    @ResponseWrapper(localName = "queryPriceAndTimeResponse", targetNamespace = "http://www.hoau.net/services/HowPriceAndTimeQueryServices", className = "net.hoau.services.howpriceandtimequeryservices.QueryPriceAndTimeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<net.hoau.services.howpriceandtimequeryservices.PriceQueryResult> queryPriceAndTime(
        @WebParam(name = "arg0", targetNamespace = "")
        net.hoau.services.howpriceandtimequeryservices.PriceQueryVo arg0
    );
}
