
package com.hoau.hoauapp.si.ttq;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-09T14:20:02.939+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class FoxServicePortType_FoxServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.foxconn.interfaces.sinotrans.com", "FoxService");

    private FoxServicePortType_FoxServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FoxService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FoxService ss = new FoxService(wsdlURL, SERVICE_NAME);
        FoxServicePortType port = ss.getFoxServiceHttpPort();  
        
        {
        System.out.println("Invoking queryPrice...");
        com.hoau.hoauapp.si.ttq.FoxPriceParamModel _queryPrice_in0 = new FoxPriceParamModel();
        _queryPrice_in0.setShipperCityName(new JAXBElement<String>(SERVICE_NAME, String.class, "上海市"));
        _queryPrice_in0.setShipperCountyName(new JAXBElement<String>(SERVICE_NAME, String.class, "松江区"));
        _queryPrice_in0.setConCityName(new JAXBElement<String>(SERVICE_NAME, String.class, "郑州市"));
        _queryPrice_in0.setConCountyName(new JAXBElement<String>(SERVICE_NAME, String.class, "金水区"));
        com.hoau.hoauapp.si.ttq.FoxPriceResult _queryPrice__return = port.queryPrice(_queryPrice_in0);
        System.out.println("queryPrice.result=" + _queryPrice__return);


        }
//        {
//        System.out.println("Invoking queryGoodsTrack...");
//        java.lang.String _queryGoodsTrack_in0 = "";
//        com.hoau.hoauapp.si.ttq.FoxTraceResult _queryGoodsTrack__return = port.queryGoodsTrack(_queryGoodsTrack_in0);
//        System.out.println("queryGoodsTrack.result=" + _queryGoodsTrack__return);
//
//
//        }
//        {
//        System.out.println("Invoking createOrder...");
//        com.hoau.hoauapp.si.ttq.FoxOrderModel _createOrder_in0 = null;
//        com.hoau.hoauapp.si.ttq.FoxCreateOrderResult _createOrder__return = port.createOrder(_createOrder_in0);
//        System.out.println("createOrder.result=" + _createOrder__return);
//
//
//        }

        System.exit(0);
    }

}
