
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.hoauapp.si.ttq;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-09T14:20:02.959+08:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "FoxService",
                      portName = "FoxServiceHttpPort",
                      targetNamespace = "http://service.foxconn.interfaces.sinotrans.com",
                      wsdlLocation = "http://10.39.251.105/HOAU_OL/services/FoxService?wsdl",
                      endpointInterface = "com.hoau.hoauapp.si.ttq.FoxServicePortType")
                      
public class FoxServiceHttpPortImpl implements FoxServicePortType {

    private static final Logger LOG = Logger.getLogger(FoxServiceHttpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.ttq.FoxServicePortType#queryPrice(com.hoau.hoauapp.si.ttq.FoxPriceParamModel  in0 )*
     */
    public com.hoau.hoauapp.si.ttq.FoxPriceResult queryPrice(com.hoau.hoauapp.si.ttq.FoxPriceParamModel in0) { 
        LOG.info("Executing operation queryPrice");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.ttq.FoxPriceResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.ttq.FoxServicePortType#queryGoodsTrack(java.lang.String  in0 )*
     */
    public com.hoau.hoauapp.si.ttq.FoxTraceResult queryGoodsTrack(java.lang.String in0) { 
        LOG.info("Executing operation queryGoodsTrack");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.ttq.FoxTraceResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.ttq.FoxServicePortType#createOrder(com.hoau.hoauapp.si.ttq.FoxOrderModel  in0 )*
     */
    public com.hoau.hoauapp.si.ttq.FoxCreateOrderResult createOrder(com.hoau.hoauapp.si.ttq.FoxOrderModel in0) { 
        LOG.info("Executing operation createOrder");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.ttq.FoxCreateOrderResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
