package com.hoau.hoauapp.si.ttq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-15T15:18:17.743+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://service.foxconn.interfaces.sinotrans.com", name = "FoxServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface FoxServicePortType {

    @WebResult(name = "out", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryPrice", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ttq.QueryPrice")
    @WebMethod
    @ResponseWrapper(localName = "queryPriceResponse", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ttq.QueryPriceResponse")
    public com.hoau.hoauapp.si.ttq.FoxPriceResult queryPrice(
        @WebParam(name = "in0", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.ttq.FoxPriceParamModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryGoodsTrack", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ttq.QueryGoodsTrack")
    @WebMethod
    @ResponseWrapper(localName = "queryGoodsTrackResponse", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ttq.QueryGoodsTrackResponse")
    public com.hoau.hoauapp.si.ttq.FoxTraceResult queryGoodsTrack(
        @WebParam(name = "in0", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com")
        java.lang.String in0
    );

    @WebResult(name = "out", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ttq.CreateOrder")
    @WebMethod
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.ttq.CreateOrderResponse")
    public com.hoau.hoauapp.si.ttq.FoxCreateOrderResult createOrder(
        @WebParam(name = "in0", targetNamespace = "http://service.foxconn.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.ttq.FoxOrderModel in0
    );
}
