package com.hoau.hoauapp.si.ttq;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-15T15:18:17.774+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "FoxService", 
                  wsdlLocation = "http://ttq.hoau.net:9080/services/FoxService?wsdl",
                  targetNamespace = "http://service.foxconn.interfaces.sinotrans.com") 
public class FoxService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.foxconn.interfaces.sinotrans.com", "FoxService");
    public final static QName FoxServiceHttpPort = new QName("http://service.foxconn.interfaces.sinotrans.com", "FoxServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://ttq.hoau.net:9080/services/FoxService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FoxService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ttq.hoau.net:9080/services/FoxService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FoxService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FoxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FoxService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public FoxService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    public FoxService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public FoxService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }    




    /**
     *
     * @return
     *     returns FoxServicePortType
     */
    @WebEndpoint(name = "FoxServiceHttpPort")
    public FoxServicePortType getFoxServiceHttpPort() {
        return super.getPort(FoxServiceHttpPort, FoxServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FoxServicePortType
     */
    @WebEndpoint(name = "FoxServiceHttpPort")
    public FoxServicePortType getFoxServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(FoxServiceHttpPort, FoxServicePortType.class, features);
    }

}
