package com.hoau.hoauapp.si.claim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-24T14:56:24.346+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://hoauapp.ws.erry.com/", name = "ClaimsWSService")
@XmlSeeAlso({ObjectFactory.class})
public interface ClaimsWSService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findClaimsDetail", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.FindClaimsDetail")
    @WebMethod
    @ResponseWrapper(localName = "findClaimsDetailResponse", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.FindClaimsDetailResponse")
    public com.hoau.hoauapp.si.claim.ResponseQueryDetail findClaimsDetail(
        @WebParam(name = "billNo", targetNamespace = "")
        java.lang.String billNo,
        @WebParam(name = "claimsNo", targetNamespace = "")
        java.lang.String claimsNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmClaimsAmount", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.ConfirmClaimsAmount")
    @WebMethod
    @ResponseWrapper(localName = "confirmClaimsAmountResponse", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.ConfirmClaimsAmountResponse")
    public com.hoau.hoauapp.si.claim.ResponseClaimsObject confirmClaimsAmount(
        @WebParam(name = "claimsNo", targetNamespace = "")
        java.lang.String claimsNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findByClaims", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.FindByClaims")
    @WebMethod
    @ResponseWrapper(localName = "findByClaimsResponse", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.FindByClaimsResponse")
    public com.hoau.hoauapp.si.claim.ResponseQueryFiles findByClaims(
        @WebParam(name = "billNo", targetNamespace = "")
        java.lang.String billNo,
        @WebParam(name = "claimsNo", targetNamespace = "")
        java.lang.String claimsNo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClaims", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.GetClaims")
    @WebMethod
    @ResponseWrapper(localName = "getClaimsResponse", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.GetClaimsResponse")
    public com.hoau.hoauapp.si.claim.ResponseQueryClaims getClaims(
        @WebParam(name = "userID", targetNamespace = "")
        java.lang.String userID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "uploadClaims", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.UploadClaims")
    @WebMethod
    @ResponseWrapper(localName = "uploadClaimsResponse", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.UploadClaimsResponse")
    public com.hoau.hoauapp.si.claim.ResponseClaimsObject uploadClaims(
        @WebParam(name = "claimsInfo", targetNamespace = "")
        com.hoau.hoauapp.si.claim.ClaimsInfo claimsInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryCheck", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.QueryCheck")
    @WebMethod
    @ResponseWrapper(localName = "queryCheckResponse", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.QueryCheckResponse")
    public com.hoau.hoauapp.si.claim.ResponseClaimsObject queryCheck(
        @WebParam(name = "reqClaimsObject", targetNamespace = "")
        com.hoau.hoauapp.si.claim.ReqClaimsObject reqClaimsObject
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findClaimsPlace", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.FindClaimsPlace")
    @WebMethod
    @ResponseWrapper(localName = "findClaimsPlaceResponse", targetNamespace = "http://hoauapp.ws.erry.com/", className = "com.hoau.hoauapp.si.claim.FindClaimsPlaceResponse")
    public java.util.List<com.hoau.hoauapp.si.claim.QueryCorpResult> findClaimsPlace(
        @WebParam(name = "billNo", targetNamespace = "")
        java.lang.String billNo,
        @WebParam(name = "billTel", targetNamespace = "")
        java.lang.String billTel
    );
}
