package com.hoau.hoauapp.si.oms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-12-08T10:01:28.524+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "MobileService", 
                  wsdlLocation = "http://10.39.251.184:8180/obh-web/services/MobileService?wsdl",
                  targetNamespace = "http://mobile.impl.service.server.itf.module.obh.hoau.com/") 
public class MobileService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://mobile.impl.service.server.itf.module.obh.hoau.com/", "MobileService");
    public final static QName MobileServiceImplPort = new QName("http://mobile.impl.service.server.itf.module.obh.hoau.com/", "MobileServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.184:8180/obh-web/services/MobileService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MobileService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.184:8180/obh-web/services/MobileService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MobileService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MobileService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MobileService
     */
    @WebEndpoint(name = "MobileServiceImplPort")
    public MobileService getMobileServiceImplPort() {
        return super.getPort(MobileServiceImplPort, MobileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileService
     */
    @WebEndpoint(name = "MobileServiceImplPort")
    public MobileService getMobileServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MobileServiceImplPort, MobileService.class, features);
    }

}
