package com.hoau.hoauapp.si.bank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-27T10:36:53.372+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "BaseAccountInfoServices", 
                  wsdlLocation = "http://10.39.251.3:8080/hoaunew/services/BaseAccountInfoServices?wsdl",
                  targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices") 
public class BaseAccountInfoServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://10.39.251.150:8080/services/BaseAccountInfoServices", "BaseAccountInfoServices");
    public final static QName BaseAccountInfoServicesPort = new QName("http://10.39.251.150:8080/services/BaseAccountInfoServices", "BaseAccountInfoServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.3:8080/hoaunew/services/BaseAccountInfoServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaseAccountInfoServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.3:8080/hoaunew/services/BaseAccountInfoServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BaseAccountInfoServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaseAccountInfoServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaseAccountInfoServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BaseAccountInfoServices_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaseAccountInfoServices_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    public BaseAccountInfoServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }    




    /**
     *
     * @return
     *     returns BaseAccountInfoServices
     */
    @WebEndpoint(name = "BaseAccountInfoServicesPort")
    public BaseAccountInfoServices getBaseAccountInfoServicesPort() {
        return super.getPort(BaseAccountInfoServicesPort, BaseAccountInfoServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseAccountInfoServices
     */
    @WebEndpoint(name = "BaseAccountInfoServicesPort")
    public BaseAccountInfoServices getBaseAccountInfoServicesPort(WebServiceFeature... features) {
        return super.getPort(BaseAccountInfoServicesPort, BaseAccountInfoServices.class, features);
    }

}
