
package com.hoau.hoauapp.si.dc.company;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-15T09:12:56.146+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class CompanyServices_CompanyServicesPort_Server{

    protected CompanyServices_CompanyServicesPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CompanyServicesImpl();
        String address = "http://10.39.109.29:8080/services/CompanyServices";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new CompanyServices_CompanyServicesPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
