package com.hoau.hoauapp.si.dc.sendme;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-06-16T15:49:23.720+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "AppWaybillServices", 
                  wsdlLocation = "http://10.39.251.3:8080/hoaunew/services/AppWaybillServices?wsdl",
                  targetNamespace = "http://www.hoau.net/services/AppWaybillServices") 
public class AppWaybillServices_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.hoau.net/services/AppWaybillServices", "AppWaybillServices");
    public final static QName AppWaybillServicesPort = new QName("http://www.hoau.net/services/AppWaybillServices", "AppWaybillServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.39.251.3:8080/hoaunew/services/AppWaybillServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AppWaybillServices_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.39.251.3:8080/hoaunew/services/AppWaybillServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AppWaybillServices_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppWaybillServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppWaybillServices_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AppWaybillServices
     */
    @WebEndpoint(name = "AppWaybillServicesPort")
    public AppWaybillServices getAppWaybillServicesPort() {
        return super.getPort(AppWaybillServicesPort, AppWaybillServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppWaybillServices
     */
    @WebEndpoint(name = "AppWaybillServicesPort")
    public AppWaybillServices getAppWaybillServicesPort(WebServiceFeature... features) {
        return super.getPort(AppWaybillServicesPort, AppWaybillServices.class, features);
    }

}
