
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.hoauapp.si.oms;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-08-21T11:07:27.344+08:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "MobileService",
                      portName = "MobileServiceHttpPort",
                      targetNamespace = "http://services.mobile.interfaces.sinotrans.com",
                      wsdlLocation = "http://testoms.hoau.net/HOAU_OL/services/MobileService?wsdl",
                      endpointInterface = "com.hoau.hoauapp.si.oms.MobileServicePortType")
                      
public class MobileServicePortTypeImpl implements MobileServicePortType {

    private static final Logger LOG = Logger.getLogger(MobileServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#queryOrderDetail(com.hoau.hoauapp.si.oms.GetPhoneOrderReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.GetPhoneOrderResModel queryOrderDetail(com.hoau.hoauapp.si.oms.GetPhoneOrderReqModel in0) { 
        LOG.info("Executing operation queryOrderDetail");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.GetPhoneOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#cancelPhoneOrde(com.hoau.hoauapp.si.oms.CancelOrderReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.CancelOrderResModel cancelPhoneOrde(com.hoau.hoauapp.si.oms.CancelOrderReqModel in0) { 
        LOG.info("Executing operation cancelPhoneOrde");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.CancelOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#resetPwd(com.hoau.hoauapp.si.oms.ResetPwdReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.ResetPwdResModel resetPwd(com.hoau.hoauapp.si.oms.ResetPwdReqModel in0) { 
        LOG.info("Executing operation resetPwd");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.ResetPwdResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#loginByPhone(com.hoau.hoauapp.si.oms.LoginUserReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.LoginUserResModel loginByPhone(com.hoau.hoauapp.si.oms.LoginUserReqModel in0) { 
        LOG.info("Executing operation loginByPhone");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.LoginUserResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#updateCache(com.hoau.hoauapp.si.oms.UpdateCacheReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.UpdateCacheResModel updateCache(com.hoau.hoauapp.si.oms.UpdateCacheReqModel in0) { 
        LOG.info("Executing operation updateCache");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.UpdateCacheResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#queryOrder(com.hoau.hoauapp.si.oms.QueryOrdersReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.QueryOrdersResModel queryOrder(com.hoau.hoauapp.si.oms.QueryOrdersReqModel in0) { 
        LOG.info("Executing operation queryOrder");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.QueryOrdersResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#modifyOrder(com.hoau.hoauapp.si.oms.ModifyOrderReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.ModifyOrderResModel modifyOrder(com.hoau.hoauapp.si.oms.ModifyOrderReqModel in0) { 
        LOG.info("Executing operation modifyOrder");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.ModifyOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#createOrder(com.hoau.hoauapp.si.oms.PhoneOrderReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.PhoneOrderResModel createOrder(com.hoau.hoauapp.si.oms.PhoneOrderReqModel in0) { 
        LOG.info("Executing operation createOrder");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.PhoneOrderResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.oms.MobileServicePortType#registerUser(com.hoau.hoauapp.si.oms.RegisterUserReqModel  in0 )*
     */
    public com.hoau.hoauapp.si.oms.RegisterUserResModel registerUser(com.hoau.hoauapp.si.oms.RegisterUserReqModel in0) { 
        LOG.info("Executing operation registerUser");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.oms.RegisterUserResModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
