package com.hoau.hoauapp.si.oms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-08-21T11:07:27.359+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://services.mobile.interfaces.sinotrans.com", name = "MobileServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface MobileServicePortType {

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryOrderDetail", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.QueryOrderDetail")
    @WebMethod
    @ResponseWrapper(localName = "queryOrderDetailResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.QueryOrderDetailResponse")
    public com.hoau.hoauapp.si.oms.GetPhoneOrderResModel queryOrderDetail(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.GetPhoneOrderReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "cancelPhoneOrde", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.CancelPhoneOrde")
    @WebMethod
    @ResponseWrapper(localName = "cancelPhoneOrdeResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.CancelPhoneOrdeResponse")
    public com.hoau.hoauapp.si.oms.CancelOrderResModel cancelPhoneOrde(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.CancelOrderReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "resetPwd", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.ResetPwd")
    @WebMethod
    @ResponseWrapper(localName = "resetPwdResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.ResetPwdResponse")
    public com.hoau.hoauapp.si.oms.ResetPwdResModel resetPwd(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.ResetPwdReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "loginByPhone", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.LoginByPhone")
    @WebMethod
    @ResponseWrapper(localName = "loginByPhoneResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.LoginByPhoneResponse")
    public com.hoau.hoauapp.si.oms.LoginUserResModel loginByPhone(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.LoginUserReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "updateCache", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.UpdateCache")
    @WebMethod
    @ResponseWrapper(localName = "updateCacheResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.UpdateCacheResponse")
    public com.hoau.hoauapp.si.oms.UpdateCacheResModel updateCache(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.UpdateCacheReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "queryOrder", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.QueryOrder")
    @WebMethod
    @ResponseWrapper(localName = "queryOrderResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.QueryOrderResponse")
    public com.hoau.hoauapp.si.oms.QueryOrdersResModel queryOrder(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.QueryOrdersReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "modifyOrder", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.ModifyOrder")
    @WebMethod
    @ResponseWrapper(localName = "modifyOrderResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.ModifyOrderResponse")
    public com.hoau.hoauapp.si.oms.ModifyOrderResModel modifyOrder(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.ModifyOrderReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.CreateOrder")
    @WebMethod
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.CreateOrderResponse")
    public com.hoau.hoauapp.si.oms.PhoneOrderResModel createOrder(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.PhoneOrderReqModel in0
    );

    @WebResult(name = "out", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.RegisterUser")
    @WebMethod
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://services.mobile.interfaces.sinotrans.com", className = "com.hoau.hoauapp.si.oms.RegisterUserResponse")
    public com.hoau.hoauapp.si.oms.RegisterUserResModel registerUser(
        @WebParam(name = "in0", targetNamespace = "http://services.mobile.interfaces.sinotrans.com")
        com.hoau.hoauapp.si.oms.RegisterUserReqModel in0
    );
}
