
package com.hoau.hoauapp.si.oms;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-08-21T11:07:27.367+08:00
 * Generated source version: 2.7.11
 * 
 */
 
public class MobileServicePortType_MobileServiceHttpPort_Server{

    protected MobileServicePortType_MobileServiceHttpPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new MobileServicePortTypeImpl();
        String address = "http://testoms.hoau.net/HOAU_OL/services/MobileService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new MobileServicePortType_MobileServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
