
package com.hoau.hoauapp.si.newoms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-11-04T11:58:01.419+08:00
 * Generated source version: 2.7.14
 * 
 */
public final class AppServicePortType_AppServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.app.interfaces.sinotrans.com", "AppService");

    private AppServicePortType_AppServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AppService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AppService_Service ss = new AppService_Service(wsdlURL, SERVICE_NAME);
        AppService port = ss.getAppServiceImplPort();  
        
        {
        System.out.println("Invoking createOrder...");
        com.hoau.hoauapp.si.newoms.OrderModel _createOrder_in0 = null;
        com.hoau.hoauapp.si.newoms.PhoneOrderResModel _createOrder__return = port.createOrder(_createOrder_in0);
        System.out.println("createOrder.result=" + _createOrder__return);


        }
        {
        System.out.println("Invoking queryOrder...");
        com.hoau.hoauapp.si.newoms.QueryOrdersReqModel _queryOrder_in0 = null;
        com.hoau.hoauapp.si.newoms.QueryAppOrdersResModel _queryOrder__return = port.queryOrder(_queryOrder_in0);
        System.out.println("queryOrder.result=" + _queryOrder__return);


        }
        {
        System.out.println("Invoking modifyOrder...");
        com.hoau.hoauapp.si.newoms.OrderModel _modifyOrder_in0 = null;
        com.hoau.hoauapp.si.newoms.ModifyOrderResModel _modifyOrder__return = port.modifyOrder(_modifyOrder_in0);
        System.out.println("modifyOrder.result=" + _modifyOrder__return);


        }
        {
        System.out.println("Invoking queryUserInfo...");
        java.lang.String _queryUserInfo_in0 = "";
        com.hoau.hoauapp.si.newoms.QueryUserResModel _queryUserInfo__return = port.queryUserInfo(_queryUserInfo_in0);
        System.out.println("queryUserInfo.result=" + _queryUserInfo__return);


        }
        {
        System.out.println("Invoking resetPwd...");
        com.hoau.hoauapp.si.newoms.ResetPwdReqModel _resetPwd_in0 = null;
        com.hoau.hoauapp.si.newoms.ResetPwdResModel _resetPwd__return = port.resetPwd(_resetPwd_in0);
        System.out.println("resetPwd.result=" + _resetPwd__return);


        }

        System.exit(0);
    }

}
