
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.hoau.hoauapp.si.ol;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-10-29T15:52:16.532+08:00
 * Generated source version: 2.7.14
 * 
 */

@javax.jws.WebService(
                      serviceName = "DistrictService",
                      portName = "DistrictServiceHttpPort",
                      targetNamespace = "http://services.district.interfaces.sinotrans.com",
                      wsdlLocation = "http://online.hoau.net/obh-web/services/DistrictService?wsdl",
                      endpointInterface = "com.hoau.hoauapp.si.ol.DistrictServicePortType")
                      
public class DistrictServicePortTypeImpl implements DistrictServicePortType {

    private static final Logger LOG = Logger.getLogger(DistrictServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.ol.DistrictServicePortType#queryProvince(*
     */
    public com.hoau.hoauapp.si.ol.ArrayOfDistrictModel queryProvince() { 
        LOG.info("Executing operation queryProvince");
        try {
            com.hoau.hoauapp.si.ol.ArrayOfDistrictModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.ol.DistrictServicePortType#queryCityByProvince(java.lang.String  in0 )*
     */
    public com.hoau.hoauapp.si.ol.ArrayOfDistrictModel queryCityByProvince(java.lang.String in0) { 
        LOG.info("Executing operation queryCityByProvince");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.ol.ArrayOfDistrictModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.ol.DistrictServicePortType#queryDeptByDistrict(java.lang.String  in0 ,)java.lang.String  in1 ,)java.lang.String  in2 ,)java.lang.String  in3 ,)java.lang.String  in4 ,)java.lang.String  in5 )*
     */
    public java.lang.String queryDeptByDistrict(java.lang.String in0,java.lang.String in1,java.lang.String in2,java.lang.String in3,java.lang.String in4,java.lang.String in5) { 
        LOG.info("Executing operation queryDeptByDistrict");
        System.out.println(in0);
        System.out.println(in1);
        System.out.println(in2);
        System.out.println(in3);
        System.out.println(in4);
        System.out.println(in5);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.hoau.hoauapp.si.ol.DistrictServicePortType#queryCountyByCity(java.lang.String  in0 )*
     */
    public com.hoau.hoauapp.si.ol.ArrayOfDistrictModel queryCountyByCity(java.lang.String in0) { 
        LOG.info("Executing operation queryCountyByCity");
        System.out.println(in0);
        try {
            com.hoau.hoauapp.si.ol.ArrayOfDistrictModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
