package com.hoau.hoauapp.si.bank;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-27T10:36:53.346+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", name = "BaseAccountInfoServices")
@XmlSeeAlso({ObjectFactory.class})
public interface BaseAccountInfoServices {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://10.39.251.150:8080/services/BaseAccountInfoServices/BaseAccountInfoServices/getAccountCityListRequest", output = "http://10.39.251.150:8080/services/BaseAccountInfoServices/BaseAccountInfoServices/getAccountCityListResponse")
    @RequestWrapper(localName = "getAccountCityList", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.hoauapp.si.bank.GetAccountCityList")
    @WebMethod
    @ResponseWrapper(localName = "getAccountCityListResponse", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.hoauapp.si.bank.GetAccountCityListResponse")
    public java.util.List<com.hoau.hoauapp.si.bank.AccountCity> getAccountCityList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://10.39.251.150:8080/services/BaseAccountInfoServices/BaseAccountInfoServices/getAccountProvinceListRequest", output = "http://10.39.251.150:8080/services/BaseAccountInfoServices/BaseAccountInfoServices/getAccountProvinceListResponse")
    @RequestWrapper(localName = "getAccountProvinceList", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.hoauapp.si.bank.GetAccountProvinceList")
    @WebMethod
    @ResponseWrapper(localName = "getAccountProvinceListResponse", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.hoauapp.si.bank.GetAccountProvinceListResponse")
    public java.util.List<com.hoau.hoauapp.si.bank.AccountProvince> getAccountProvinceList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://10.39.251.150:8080/services/BaseAccountInfoServices/BaseAccountInfoServices/getAccountBankInfoListRequest", output = "http://10.39.251.150:8080/services/BaseAccountInfoServices/BaseAccountInfoServices/getAccountBankInfoListResponse")
    @RequestWrapper(localName = "getAccountBankInfoList", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.hoauapp.si.bank.GetAccountBankInfoList")
    @WebMethod
    @ResponseWrapper(localName = "getAccountBankInfoListResponse", targetNamespace = "http://10.39.251.150:8080/services/BaseAccountInfoServices", className = "com.hoau.hoauapp.si.bank.GetAccountBankInfoListResponse")
    public java.util.List<com.hoau.hoauapp.si.bank.AccountBankInfo> getAccountBankInfoList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
